version: "3.8"

services:
  libros:
    build: .
    container_name: libros
    volumes:
      - .:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - libros-db
    networks:
      - app-network

  libros-db:
    image: mysql:latest
    container_name: "libros-db"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: libros
      MYSQL_USER: root
      MYSQL_PASSWORD: "123456"
    tty: true
    ports:
      - 3306:3306
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
